language: php

php:
  - 5.3
  - 5.4
before_script: 
  - php vendor/travis_before_script.php
  - cd  ../../ActivDev/NoclineBundle/
  
script: phpunit  
  
notifications:
  email:
    - bruno@activdev.com
    - codes.bruno@gmail.com
